[package]
name = "kbhell"
version = "0.1.0"
edition = "2021"
description = "Annoy everyone around you by playing noises everytime you press a key."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
rodio = "0.20.1"
