cmake_minimum_required(VERSION 3.27)

# Force SDL_mixer to build the static version of the lib.
set(SDL2MIXER_DEPS_SHARED OFF CACHE INTERNAL "")
set(BUILD_SHARED_LIBS OFF CACHE INTERNAL "")

# Turn off a number of options to speed up the build. We really only need the
# WAV functionality of SDL_mixer, all other functions can be disabled.
set(SDL2MIXER_VENDORED ON CACHE INTERNAL "use vendored (not system) libs")
set(SDL2MIXER_FLAC OFF CACHE INTERNAL "")
set(SDL2MIXER_MIDI OFF CACHE INTERNAL "")
set(SDL2MIXER_MIDI_FLUIDSYNTH OFF CACHE INTERNAL "")
set(SDL2MIXER_MIDI_FLUIDSYNTH_SHARED OFF CACHE INTERNAL "")
set(SDL2MIXER_MIDI_TIMIDITY OFF CACHE INTERNAL "")
set(SDL2MIXER_MOD OFF CACHE INTERNAL "")
set(SDL2MIXER_MOD_MODPLUG OFF CACHE INTERNAL "")
set(SDL2MIXER_MOD_XMP OFF CACHE INTERNAL "")
set(SDL2MIXER_MOD_XMP_LITE OFF CACHE INTERNAL "")
set(SDL2MIXER_MOD_XMP_SHARED OFF CACHE INTERNAL "")
set(SDL2MIXER_MP3 OFF CACHE INTERNAL "")
set(SDL2MIXER_MP3_DRMP3 OFF CACHE INTERNAL "")
set(SDL2MIXER_MP3_MPG123 OFF CACHE INTERNAL "")
set(SDL2MIXER_OPUS OFF CACHE INTERNAL "")
